# Generated by Django 3.0 on 2019-12-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='author',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='text',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.Person')),
            ],
            bases=('base_app.person',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('passenger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_app.Passenger')),
            ],
            bases=('base_app.passenger',),
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(related_name='not_driving_passengers', to='base_app.Passenger'),
        ),
        migrations.AddField(
            model_name='trip',
            name='drivers',
            field=models.ManyToManyField(related_name='driving_passengers', to='base_app.Driver'),
        ),
    ]
