# Generated by Django 3.0 on 2019-12-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20191204_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='starting_point',
            field=models.CharField(default='', max_length=100),
        ),
    ]
