# Generated by Django 3.0 on 2019-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_destinationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverform',
            name='starting_point',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passengerform',
            name='starting_point',
            field=models.CharField(max_length=200),
        ),
    ]
