# Generated by Django 3.0 on 2019-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20191209_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationform',
            name='destination',
        ),
        migrations.AddField(
            model_name='destinationform',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='destinationform',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='destinationform',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='destinationform',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
