# Generated by Django 3.0 on 2019-12-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_auto_20191210_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinationForm',
        ),
        migrations.DeleteModel(
            name='DriverForm',
        ),
    ]
