# Generated by Django 3.0 on 2019-12-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_auto_20191211_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassengerForm',
        ),
    ]
