# Generated by Django 3.0 on 2019-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_delete_passengerform'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='country_code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='starting_point',
            field=models.CharField(default='', max_length=200),
        ),
    ]
