# Generated by Django 3.0 on 2019-12-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_cell_matrix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Matrix',
        ),
    ]
